# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://dev.to/n3wt0n/container-image-promotion-across-environments-yaml-1ca6

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'
  ImageName: 'hauki'
  azureSubscription: HKI-kanslia-standalone
  appName: hauki
  containerRegistry: registry.hub.docker.com

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build the images
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - script: |
          echo 'Running in workspace $(Pipeline.Workspace)'
          echo 'Build.SourceVersion: $(Build.SourceVersion)'
          echo 'Build.SourceVersionMessage: $(Build.SourceVersionMessage)'
          echo 'Build.SourcesDirectory: $(Build.SourcesDirectory)'
          echo 'Build.ArtifactStagingDirectory: $(build.artifactstagingdirectory)'
    - task: DockerCompose@0
      displayName: Build images
      inputs:
        dockerComposeCommand: build
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        includeSourceTags: true
        includeLatestTag: true
    - task: Docker@2
      displayName: Save deployment image to TAR
      inputs:
        repository: '$(ImageName)'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName)'
        addPipelineData: false
    - task: Docker@2
      displayName: Save dev/test image to TAR
      inputs:
        repository: '$(ImageName)_dev'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName)_dev.image.tar $(ImageName)_dev'
        addPipelineData: false
    - publish: $(build.artifactstagingdirectory)
      artifact: ContainerImages
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test the dev image
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download images
        inputs:
          artifact: ContainerImages
      - task: Docker@2
        displayName: Load dev image from Tar
        inputs:
          command: load
          arguments: '--input $(Pipeline.Workspace)/$(ImageName)_dev.image.tar'
      - task: DockerCompose@0
        displayName: Run tests
        inputs:
          dockerComposeCommand: run dev test
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push deploy image to registry
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download images
        inputs:
          artifact: ContainerImages
      - task: Docker@2
        displayName: Load production image from Tar
        inputs:
          command: load
          arguments: '--input $(Pipeline.Workspace)/$(ImageName).image.tar'
      - task: Docker@2
        displayName: Rename the image
        inputs:
          containerRegistry: Docker hub upload
          repository: $(ImageName)
          command: tag
          arguments: $(ImageName):latest helsinki/$(ImageName):latest
      - task: Docker@2
        displayName: Rename the image
        inputs:
          containerRegistry: Docker hub upload
          repository: $(ImageName)
          command: tag
          arguments: $(ImageName):latest helsinki/$(ImageName):$(tag)
      - task: Docker@2
        displayName: Push image to Docker hub
        inputs:
          containerRegistry: Docker hub upload
          repository: helsinki/$(ImageName)
          command: push
          tags: |
            latest
            $(tag)
- stage: Deploy
  displayName: Deploy to Azure Webapp
  jobs:
    - deployment: DeployWeb
      displayName: Deploy Web App
      pool:
        vmImage: Ubuntu-18.04
      # creates an environment if it doesn't exist
      environment: $(appName)Test
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
              - task: AzureWebAppContainer@1
                displayName: Azure Web App on Container Deploy
                inputs:
                  appName: $(appName)-test
                  azureSubscription: $(azureSubscription)
                  imageName: $(containerRegistry)/helsinki/$(imageName)
