# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://dev.to/n3wt0n/container-image-promotion-across-environments-yaml-1ca6

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'cityofhelsinkihauki'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build the images
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DockerCompose@0
      displayName: Build images
      inputs:
        dockerComposeCommand: build
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        additionalImageTags: $(tag)
    - task: Docker@2
      displayName: Save django image to TAR
      inputs:
        repository: '$(ImageName)_django'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName)_django.image.tar $(ImageName)_django:latest'
        addPipelineData: false
    - task: Docker@2
      displayName: Save test image to TAR
      inputs:
        repository: '$(ImageName)_test'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName)_test.image.tar $(ImageName)_test:latest'
        addPipelineData: false
    - task: PublishPipelineArtifact@1
      displayName: Publishing Image as Pipeline Artifact
      inputs:
        path: $(build.artifactstagingdirectory)
        artifact: 'ContainerImage'
- stage: Test
  displayName: Test
  jobs:
  - deployment: Test
    displayName: Test
    environment: HaukiTest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Docker@2
              displayName: Load test image from Tar
              inputs:
                command: load
                arguments: '--input $(Pipeline.Workspace)/ContainerImage/$(ImageName)_test.image.tar'
            - task: DockerCompose@0
              displayName: Run tests
              inputs:
                dockerComposeCommand: run test
                dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
                tags: |
                  $(tag)