# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DockerCompose@0
      displayName: Build an image
      inputs:
        dockerComposeCommand: build
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        tags: |
          $(tag)
    - task: DockerCompose@0
      displayName: Run tests
      inputs:
        dockerComposeCommand: run test
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        tags: |
          $(tag)